spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:one4all.cp2u0w48kyqy.ap-south-1.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:one4all}?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
  main:
    allow-bean-definition-overriding: 'true'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    activate:
      on-profile: dev

server:
  port: 443
  address: 0.0.0.0
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: one4all-backend

id:
  prefix: O4AA4O
  number-length: '7'

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
        web: DEBUG
        http:
          converter:
            json: DEBUG
    com:
      zaxxer:
        hikari: DEBUG
      mysql:
        cj: TRACE

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:https://one4all-all4one.com}
    methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}

mlm:
  bonus:
    direct:
      referral: '1000'
  payout:
    L1: '2000'
    L2: '1000'
    L3: '1000'
    L4: '2500'
    L5: '5000'
    L6: '10000'
    L7: '20000'
    L8: '30000'
    L9: '40000'
    L10: '50000'

microservice:
  url: ${MICROSERVICE_URL:https://api.one4all-all4one.com}
  clientid: ${MICROSERVICE_CLIENTID:one4all}
  clientsecret: ${MICROSERVICE_CLIENTSECRET:Oldisgold@2025}
  scope: ${MICROSERVICE_SCOPE:read,write}

rsa:
  private:
    key: keys/private.pem
  public:
    key: keys/public.pem

aws:
  ses:
    region: ${AWS_SES_REGION:ap-south-1}
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    verified-sender: ${AWS_SES_VERIFIED_SENDER}

frontend:
  reset-password:
    base-url: ${FRONTEND_RESET_PASSWORD_BASE_URL:https://one4all-all4one.com/reset-password/confirm/}

upload:
  dir: ${UPLOAD_DIR:uploads}