spring:
  application:
    name: one4all-backend

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:one4all}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
      leak-detection-threshold: 3000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always
    health:
      db:
        enabled: true
      diskspace:
        enabled: true
      ping:
        enabled: true
server:
  port: 8080
microservice:
  url: ${MICROSERVICE_URL}
  clientid: ${MICROSERVICE_CLIENTID}
  clientsecret: ${MICROSERVICE_CLIENTSECRET}
  scope: ${MICROSERVICE_SCOPE}
rsa:
  private:
    key: ${RSA_PRIVATE_KEY_PATH}
  public:
    key: ${RSA_PUBLIC_KEY_PATH}
aws:
  ses:
    region: ${AWS_SES_REGION}
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    verified-sender: ${AWS_SES_VERIFIED_SENDER}
frontend:
  reset-password:
    base-url: ${FRONTEND_RESET_PASSWORD_BASE_URL}
  base-url: ${FRONTEND_BASE_URL}
upload:
  dir: ${UPLOAD_DIR}