spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
  main:
    allow-bean-definition-overriding: 'true'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    activate:
      on-profile: dev

server:
  port: 443
  address: 0.0.0.0
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS}

id:
  prefix: O4AA4O
  number-length: '7'

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
        web: DEBUG
        http:
          converter:
            json: DEBUG
    com:
      zaxxer:
        hikari: DEBUG
      mysql:
        cj: TRACE

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:https://one4all-all4one.com}
    methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}

mlm:
  bonus:
    direct:
      referral: '1000'
  payout:
    L1: '2000'
    L2: '1000'
    L3: '1000'
    L4: '2500'
    L5: '5000'
    L6: '10000'
    L7: '20000'
    L8: '30000'
    L9: '40000'
    L10: '50000'

microservice:
  url: ${MICROSERVICE_URL}
  clientid: ${MICROSERVICE_CLIENTID}
  clientsecret: ${MICROSERVICE_CLIENTSECRET}
  scope: ${MICROSERVICE_SCOPE}
rsa:
  private:
    key: ${RSA_PRIVATE_KEY_PATH}
  public:
    key: ${RSA_PUBLIC_KEY_PATH}
aws:
  ses:
    region: ${AWS_SES_REGION}
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    verified-sender: ${AWS_SES_VERIFIED_SENDER}
frontend:
  reset-password:
    base-url: ${FRONTEND_RESET_PASSWORD_BASE_URL}
  base-url: ${FRONTEND_BASE_URL}
upload:
  dir: ${UPLOAD_DIR}